name: README Spell Check

on: [push]

jobs:
  Spell-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rojopolis/spellcheck-github-actions@0.44.0
        name: Spellcheck
        with:
          config_path: .spellchecking.yml
          source_files: README.md Code%20Style%20Guidelines.md
          task_name: Markdown